---
- name: debian | Installing Pre-Reqs
  apt:
    name: ["gnupg2"]
    state: present
  become: true
  register: result
  until: result is successful

- name: debian | Adding PBIS Open Repo Key
  apt_key:
    url: "{{ pbis_open_debian_repo_key }}"
    state: present
  become: true
  register: result
  until: result is successful

- name: debian | Adding PBIS Open Repo
  apt_repository:
    repo: "{{ pbis_open_debian_repo }}"
    state: present
  become: true
  register: result
  until: result is successful

- name: debian | Installing PBIS Open
  apt:
    name: ["pbis-open"]
    state: present
  become: true
  register: result
  until: result is successful
